modLoader = "javafml"
loaderVersion = "[47,)"
license = "GNU LGPL 3.0"
issueTrackerURL = "https://github.com/IAFEnvoy/RainimatorMod/issues"
[[mods]]
modId = "rainimator"
version = "${version}"
displayName = "Rainimator Mod"
logoFile = "logo.jpg"
authors = "Triceratops, IAFEnvoy"
description = '''
Rainimator Minecraft Animation mod. @Rainimator @Rainolaguer
'''
[[dependencies.rainimator]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.rainimator]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
[[dependencies.rainimator]]
modId = "architectury"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.rainimator]]
modId = "curios"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.rainimator]]
modId = "neptune"
mandatory = true
versionRange = "[0.3.1,)"
ordering = "NONE"
side = "BOTH"