package com.rainimator.rainimatormod.registry;

import com.rainimator.rainimatormod.RainimatorMod;
import com.rainimator.rainimatormod.armor.*;
import com.rainimator.rainimatormod.item.*;
import com.rainimator.rainimatormod.item.shield.*;
import com.rainimator.rainimatormod.item.sword.*;
import com.rainimator.rainimatormod.item.tool.*;
import com.rainimator.rainimatormod.registry.util.*;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class ModItems {
    public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, RainimatorMod.MOD_ID);
    //resources
    public static final RegistryObject<Item> SUPER_RUBY = REGISTRY.register("super_ruby", () -> new ItemBase(p -> p.tab(ModCreativeTab.items).fireResistant()));
    public static final RegistryObject<Item> ABIGAIL_SPEAR = REGISTRY.register("abigail_spear", AbigailSpearItem::new);
    public static final RegistryObject<Item> GLUTTON_SLEDGEHAMMER = REGISTRY.register("glutton_sledgehammer", () -> new SwordItem(TierBase.of(1000, 2.0F, 8.0F, 0, 15, SUPER_RUBY), 3, -2.2F, ModCreativeTab.createProperty().fireResistant()));
    public static final RegistryObject<Item> RUBY = REGISTRY.register("ruby", () -> new ItemBase(p -> p.tab(ModCreativeTab.items)));
    public static final RegistryObject<Item> RED_GOLD_DAGGER = REGISTRY.register("red_gold_dagger", RedGoldDaggerItem::new);
    public static final RegistryObject<Item> BLACKBONE_THE_BLADE = REGISTRY.register("blackbone_the_blade", BlackBoneTheBladeItem::new);
    public static final RegistryObject<Item> BLACKBONE_THE_BLADE_DANSHOU = REGISTRY.register("blackbone_the_blade_danshou", BlackBoneTheBladeSingleHandItem::new);
    public static final RegistryObject<Item> RUBY_ORE = block(ModBlocks.RUBY_ORE);
    public static final RegistryObject<Item> DEEPSLATE_RUBY_ORE = block(ModBlocks.DEEPSLATE_RUBY_ORE);
    public static final RegistryObject<Item> RUBYBLOCK = block(ModBlocks.RUBYBLOCK);
    public static final RegistryObject<Item> RUBYBLOCKSHIT = REGISTRY.register("rubyblockshit", () -> new ItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(32)));
    public static final RegistryObject<Item> SUPER_SPPARIES = REGISTRY.register("super_spparies", () -> new ItemBase(p -> p.tab(ModCreativeTab.items).fireResistant()));
    public static final RegistryObject<Item> PATRICK_ARMOR_HELMET = REGISTRY.register("patrick_armor_helmet", PatrickArmorItem.Helmet::new);
    public static final RegistryObject<Item> PATRICK_ARMOR_CHESTPLATE = REGISTRY.register("patrick_armor_chestplate", PatrickArmorItem.Chestplate::new);
    public static final RegistryObject<Item> PATRICK_ARMOR_LEGGINGS = REGISTRY.register("patrick_armor_leggings", PatrickArmorItem.Leggings::new);
    public static final RegistryObject<Item> PATRICK_ARMOR_BOOTS = REGISTRY.register("patrick_armor_boots", PatrickArmorItem.Boots::new);
    public static final RegistryObject<Item> RAIN_SWORD = REGISTRY.register("rain_sword", RainSwordItem::new);
    public static final RegistryObject<Item> HEROBRINE_TOMAHAWK = REGISTRY.register("herobrine_tomahawk", HerobrineTomahawkItem::new);
    public static final RegistryObject<Item> ZECANIRN_THEBLADE = REGISTRY.register("zecanirn_theblade", ZecanirnThebladeItem::new);
    public static final RegistryObject<Item> END_BLADE = REGISTRY.register("end_blade", EnderBigSwordItem::new);
    public static final RegistryObject<Item> LASER_SWORD = REGISTRY.register("laser_sword", () -> new FoilSwordBase(TierBase.of(3000, 4.0F, 13.0F, 1, 18, ModItems.SUPER_SPPARIES.get(), Items.ENDER_EYE), 3, -2.4F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> MACE = REGISTRY.register("mace", () -> new SwordItem(TierBase.of(12000, 4.0F, 10.0F, 0, 10, ModItems.SUPER_SPPARIES), 3, -2.6F, ModCreativeTab.createProperty().fireResistant()));
    public static final RegistryObject<Item> SAPPRIES = REGISTRY.register("sappries", () -> new ItemBase(p -> p.tab(ModCreativeTab.items)));
    public static final RegistryObject<Item> INTELLIGENCE_TOMAHAWK = REGISTRY.register("intelligence_tomahawk", IntelligenceTomahawkItem::new);
    //sword
    public static final RegistryObject<Item> GENERAL_PATRICK_LONG_KNIVES = REGISTRY.register("general_patrick_long_knives", () -> new SwordItem(TierBase.of(2500, 4.0F, 7.0F, 0, 5, SAPPRIES), 3, -2.0F, ModCreativeTab.createProperty().fireResistant()));
    public static final RegistryObject<Item> SOLDIERS_HALBERD = REGISTRY.register("soldiers_halberd", () -> new SwordItem(TierBase.of(1500, 4.0F, 7.0F, 0, 5, SAPPRIES), 3, -2.0F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> SOLDIERS_WARHAMMER = REGISTRY.register("soldiers_warhammer", () -> new SwordItem(TierBase.of(2000, 4.0F, 6.0F, 0, 5, SAPPRIES), 3, -2.2F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> THE_BLUE_DAGGER = REGISTRY.register("the_blue_dagger", () -> new SwordItem(TierBase.of(2000, 4.0F, 5.0F, 1, 10, ModItems.SAPPRIES), 3, -2.0F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> SAPPRIES_ORE = block(ModBlocks.SAPPRIES_ORE);
    public static final RegistryObject<Item> DEEPSLATE_SAPPRIES_ORE = block(ModBlocks.DEEPSLATE_SAPPRIES_ORE);
    public static final RegistryObject<Item> SAPPRIESBLOCK = block(ModBlocks.SAPPRIESBLOCK);    //armor
    public static final RegistryObject<Item> HEROBRINE_ARMOR_CHESTPLATE = REGISTRY.register("herobrine_armor_chestplate", HerobrineArmorItem.Chestplate::new);
    public static final RegistryObject<Item> SAPPRIESBLOCKSHIT = REGISTRY.register("sappriesblockshit", () -> new ItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(32)));
    public static final RegistryObject<Item> HOT_IRON = REGISTRY.register("hot_iron", () -> new ItemBase(p -> p.tab(ModCreativeTab.items)));
    public static final RegistryObject<Item> HOT_GLOVES = REGISTRY.register("hot_gloves", HotGlovesItem::new);
    public static final RegistryObject<Item> BLUEDIAMOND = REGISTRY.register("bluediamond", BlueDiamondItem::new);
    public static final RegistryObject<Item> BLUEDIAMONDARMORS_HELMET = REGISTRY.register("bluediamondarmors_helmet", BlueDiamondArmorsItem.Helmet::new);
    public static final RegistryObject<Item> BLUEDIAMONDARMORS_CHESTPLATE = REGISTRY.register("bluediamondarmors_chestplate", BlueDiamondArmorsItem.Chestplate::new);
    public static final RegistryObject<Item> BLUEDIAMONDARMORS_LEGGINGS = REGISTRY.register("bluediamondarmors_leggings", BlueDiamondArmorsItem.Leggings::new);
    public static final RegistryObject<Item> BLUEDIAMONDARMORS_BOOTS = REGISTRY.register("bluediamondarmors_boots", BlueDiamondArmorsItem.Boots::new);
    public static final RegistryObject<Item> DIAMOND_LANCE = REGISTRY.register("diamond_lance", DiamondLanceItem::new);
    public static final RegistryObject<Item> BLUE_DIAMOND_SWORD = REGISTRY.register("blue_diamond_sword", BlueDiamondSwordItem::new);
    public static final RegistryObject<Item> WINGS_OF_SALVATION = REGISTRY.register("wings_of_salvation", WingsOfSalvationItem.Chestplate::new);
    //axe
    public static final RegistryObject<Item> DIAMOND_HATCHET = REGISTRY.register("diamond_hatchet", () -> new AxeItem(TierBase.of(1500, 4.0F, 5.0F, 2, 2, BLUEDIAMOND), 1.0F, -2.0F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> BLUEDIAMONDBLOCK = block(ModBlocks.BLUEDIAMONDBLOCK);
    public static final RegistryObject<Item> DARKOBSIDIANBLOCK = block(ModBlocks.DARKOBSIDIANBLOCK);
    public static final RegistryObject<Item> ZOMBIE_HEART = REGISTRY.register("zombie_heart", ZombieHeartItem::new);
    public static final RegistryObject<Item> WITHER_BONE = REGISTRY.register("wither_bone", () -> new ItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(16).fireResistant()));
    public static final RegistryObject<Item> LOWER_BOUND_ALLOY_BONE = REGISTRY.register("lower_bound_alloy_bone", () -> new FoilItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(16).fireResistant()));
    public static final RegistryObject<Item> ICEHEART = REGISTRY.register("iceheart", () -> new FoilItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(1).fireResistant().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> WARRIORHEART = REGISTRY.register("warriorheart", () -> new FoilItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(1).fireResistant().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> ENDERHEART = REGISTRY.register("enderheart", () -> new FoilItemBase(p -> p.tab(ModCreativeTab.items).durability(15).fireResistant().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> LIGHTHEART = REGISTRY.register("lightheart", () -> new FoilItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(1).fireResistant().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> DIAMONDPIECE = REGISTRY.register("diamondpiece", () -> new ItemBase(p -> p.tab(ModCreativeTab.items)));
    public static final RegistryObject<Item> BAOZHU = REGISTRY.register("baozhu", () -> new FoilItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(32).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> MYSTICORE = block(ModBlocks.MYSTICORE);
    public static final RegistryObject<Item> SOULPEOPLE = REGISTRY.register("soulpeople", () -> new FoilItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(32).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> ENDERSTONE = REGISTRY.register("enderstone", () -> new FoilItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(1).fireResistant().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> NEAUSSOULS = REGISTRY.register("neaussouls", () -> new FoilItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(32).fireResistant().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> ICEDHEART = REGISTRY.register("icedheart", () -> new ItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(1).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> RAINARMOR_CHESTPLATE = REGISTRY.register("rainarmor_chestplate", RainArmorItem.Chestplate::new);
    public static final RegistryObject<Item> CHIEF_OF_THE_PIG_PEOPLE_ARAMOR_HELMET = REGISTRY.register("chief_of_the_pig_people_aramor_helmet", ChiefOfThePigPeopleArmorItem.Helmet::new);
    public static final RegistryObject<Item> CHIEF_OF_THE_PIG_PEOPLE_ARAMOR_CHESTPLATE = REGISTRY.register("chief_of_the_pig_people_aramor_chestplate", ChiefOfThePigPeopleArmorItem.Chestplate::new);
    public static final RegistryObject<Item> CHIEF_OF_THE_PIG_PEOPLE_ARAMOR_LEGGINGS = REGISTRY.register("chief_of_the_pig_people_aramor_leggings", ChiefOfThePigPeopleArmorItem.Leggings::new);
    public static final RegistryObject<Item> CHIEF_OF_THE_PIG_PEOPLE_ARAMOR_BOOTS = REGISTRY.register("chief_of_the_pig_people_aramor_boots", ChiefOfThePigPeopleArmorItem.Boots::new);
    public static final RegistryObject<Item> SOLDIERS_ARMOR_HELMET = REGISTRY.register("soldiers_armor_helmet", SoldiersArmorItem.Helmet::new);
    public static final RegistryObject<Item> SOLDIERS_ARMOR_CHESTPLATE = REGISTRY.register("soldiers_armor_chestplate", SoldiersArmorItem.Chestplate::new);
    public static final RegistryObject<Item> SOLDIERS_ARMOR_LEGGINGS = REGISTRY.register("soldiers_armor_leggings", SoldiersArmorItem.Leggings::new);
    public static final RegistryObject<Item> SOLDIERS_ARMOR_BOOTS = REGISTRY.register("soldiers_armor_boots", SoldiersArmorItem.Boots::new);
    public static final RegistryObject<Item> RUBYARMOR_HELMET = REGISTRY.register("rubyarmor_helmet", RubyarmorItem.Helmet::new);
    public static final RegistryObject<Item> RUBYARMOR_CHESTPLATE = REGISTRY.register("rubyarmor_chestplate", RubyarmorItem.Chestplate::new);
    public static final RegistryObject<Item> RUBYARMOR_LEGGINGS = REGISTRY.register("rubyarmor_leggings", RubyarmorItem.Leggings::new);
    public static final RegistryObject<Item> RUBYARMOR_BOOTS = REGISTRY.register("rubyarmor_boots", RubyarmorItem.Boots::new);
    public static final RegistryObject<Item> SAPPRIESARMOR_HELMET = REGISTRY.register("sappriesarmor_helmet", SapphireArmorItem.Helmet::new);
    public static final RegistryObject<Item> SAPPRIESARMOR_CHESTPLATE = REGISTRY.register("sappriesarmor_chestplate", SapphireArmorItem.Chestplate::new);
    public static final RegistryObject<Item> SAPPRIESARMOR_LEGGINGS = REGISTRY.register("sappriesarmor_leggings", SapphireArmorItem.Leggings::new);
    public static final RegistryObject<Item> SAPPRIESARMOR_BOOTS = REGISTRY.register("sappriesarmor_boots", SapphireArmorItem.Boots::new);
    public static final RegistryObject<Item> MAGICHAT_HELMET = REGISTRY.register("magichat_helmet", MagicHatItem.Helmet::new);
    public static final RegistryObject<Item> NETHER_THE_CROWN_HELMET = REGISTRY.register("nether_the_crown_helmet", NetherTheCrownItem.Helmet::new);
    public static final RegistryObject<Item> GLUTTONARMOR_1_HELMET = REGISTRY.register("gluttonarmor_1_helmet", GluttonArmorItem.Helmet::new);
    public static final RegistryObject<Item> PIGLINKINGCROWN_HELMET = REGISTRY.register("piglinkingcrown_helmet", PiglinKingCrownItem.Helmet::new);
    public static final RegistryObject<Item> KINGNOMALCROWN_HELMET = REGISTRY.register("kingnomalcrown_helmet", KingNormalCrownItem.Helmet::new);
    public static final RegistryObject<Item> PORKSHIREKINGCROWN_HELMET = REGISTRY.register("porkshirekingcrown_helmet", PorkshireKingCrownItem.Helmet::new);
    //tool
    public static final RegistryObject<Item> RUBY_PICKAXE = REGISTRY.register("ruby_pickaxe", RubyPickaxeItem::new);
    public static final RegistryObject<Item> HEROBRINE_DIAMOND_PICKAXE = REGISTRY.register("herobrine_diamond_pickaxe", HerobrineDiamondPickaxeItem::new);
    public static final RegistryObject<Item> SUPER_DIAMOND_APPLE = REGISTRY.register("super_diamond_apple", SuperDiamondAppleItem::new);
    public static final RegistryObject<Item> NAEUS_SWORD = REGISTRY.register("naeus_sword", NaeusSwordItem::new);
    public static final RegistryObject<Item> NETHER_SPEAR = REGISTRY.register("nether_spear", NetherSpearItem::new);
    public static final RegistryObject<Item> LOWER_BOUND_ALLOY_FLAME_SABER = REGISTRY.register("lower_bound_alloy_flame_saber", LowerBoundAlloyFlameSaberItem::new);
    public static final RegistryObject<Item> LOWER_BOUND_NUCLEAR_REACTOR = REGISTRY.register("lower_bound_nuclear_reactor", LowerBoundNuclearReactorItem::new);
    public static final RegistryObject<Item> NIGHTMARES = REGISTRY.register("nightmares", NightmaresItem::new);
    public static final RegistryObject<Item> END_SATFF = REGISTRY.register("end_satff", EndStaffItem::new);
    public static final RegistryObject<Item> MAGIC_STARD = REGISTRY.register("magic_stard", () -> new ItemBase(p -> p.tab(ModCreativeTab.items).durability(5)));
    public static final RegistryObject<Item> LIGHTSWORD = REGISTRY.register("lightsword", () -> new FoilSwordBase(TierBase.of(200, 0.0F, 5.0F, 0, 25), 3, -2.2F, ModCreativeTab.createProperty().fireResistant()));
    public static final RegistryObject<Item> SHIELDEVER = REGISTRY.register("shieldever", ShieldEverItem::new);
    public static final RegistryObject<Item> DIVINECORE = REGISTRY.register("divinecore", DivinecoreItem::new);
    public static final RegistryObject<Item> SNOWSHIELD = REGISTRY.register("snowshield", SnowShieldItem::new);
    public static final RegistryObject<Item> FALLENSOULAXE = REGISTRY.register("fallensoulaxe", FallenSoulAxeItem::new);
    public static final RegistryObject<Item> SEIZINGSHADOWHALBERD = REGISTRY.register("seizingshadowhalberd", SeizingShadowHalberdItem::new);
    public static final RegistryObject<Item> ENDERBOOK = REGISTRY.register("enderbook", EnderBookItem::new);
    public static final RegistryObject<Item> COTTONCANDY = REGISTRY.register("cottoncandy", CottonCandyItem::new);
    public static final RegistryObject<Item> SAPPRIESSWORD = REGISTRY.register("sappriessword", SapphireSwordItem::new);
    public static final RegistryObject<Item> RUBYSWORD = REGISTRY.register("rubysword", RubySwordItem::new);
    public static final RegistryObject<Item> SAPPRIESAXE = REGISTRY.register("sappriesaxe", SapphireAxeItem::new);
    public static final RegistryObject<Item> RUBYAXE = REGISTRY.register("rubyaxe", RubyAxeItem::new);
    public static final RegistryObject<Item> SAPPRIESPICKAXE = REGISTRY.register("sappriespickaxe", SapphirePickaxeItem::new);
    public static final RegistryObject<Item> RUBYPICKAXE_1 = REGISTRY.register("rubypickaxe_1", RubyPickaxe1Item::new);
    public static final RegistryObject<Item> SAPPRIESSHOVEL = REGISTRY.register("sappriesshovel", SapphireShovelItem::new);
    public static final RegistryObject<Item> RUBYSHOVEL = REGISTRY.register("rubyshovel", RubyShovelItem::new);
    public static final RegistryObject<Item> SAPPRIESHOE = REGISTRY.register("sapprieshoe", SapphireHoeItem::new);
    public static final RegistryObject<Item> RUBYHOE = REGISTRY.register("rubyhoe", RubyHoeItem::new);
    public static final RegistryObject<Item> DIAMONDAPPLESUPPER = REGISTRY.register("diamondapplesupper", DiamondAppleSupperItem::new);
    public static final RegistryObject<Item> ENDERBIGSWORD = REGISTRY.register("enderbigsword", EnderCurvedSwordItem::new);
    public static final RegistryObject<Item> UNDERFLOWER = REGISTRY.register("underflower", UnderFlowerItem::new);
    public static final RegistryObject<Item> BLUEDIAMONDSHIELD = REGISTRY.register("bluediamondshield", BlueDiamondShieldItem::new);
    public static final RegistryObject<Item> BLACKGUN = REGISTRY.register("blackgun", BlackGunItem::new);
    public static final RegistryObject<Item> BLACKDEATHSWORD = REGISTRY.register("blackdeathsword", BlackDeathSwordItem::new);
    public static final RegistryObject<Item> PURIFICATION_1 = REGISTRY.register("purification_1", PurificationItem::new);
    public static final RegistryObject<Item> MYSTERIOUSGIFTBOX = REGISTRY.register("mysteriousgiftbox", MysteriousGiftBoxItem::new);
    public static final RegistryObject<Item> RAINLAZYEDSWORD = REGISTRY.register("rainlazyedsword", () -> new FoilSwordBase(TierBase.of(1500, 0.0F, 8.0F, 0, 15), 3, -2.0F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> MAGICENDERPEAL = REGISTRY.register("magicenderpeal", MagicEnderPearlItem::new);
    public static final RegistryObject<Item> SOULTOTEM = REGISTRY.register("soultotem", SoulTotemItem::new);
    public static final RegistryObject<Item> KING_ZOMBIE_PIG_MAN_SWORD = REGISTRY.register("king_zombie_pig_man_sword", () -> new SwordItem(TierBase.of(500, 0.0F, 6.0F, 0, 25, Items.GOLD_INGOT), 3, -2.3F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> EMERALD_BLADE = REGISTRY.register("emerald_blade", () -> new SwordItem(TierBase.of(1200, 4.0F, 5.0F, 0, 3, Blocks.EMERALD_BLOCK), 3, -2.2F, ModCreativeTab.createProperty().fireResistant()));
    public static final RegistryObject<Item> BLADEOFTHE_WHIRLWIND = REGISTRY.register("bladeofthe_whirlwind", () -> new SwordItem(TierBase.of(2500, 4.0F, 6.0F, 0, 2, Blocks.OAK_LEAVES), 3, -2.8F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> SNOW_DIAMOND_SWORD = REGISTRY.register("snow_diamond_sword", () -> new SwordItem(TierBase.of(3000, 4.0F, 6.0F, 0, 2, Blocks.SNOW_BLOCK), 3, -2.0F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> NETHER_SICKLE = REGISTRY.register("nether_sickle", () -> new SwordItem(TierBase.of(2000, 4.0F, 3.0F, 1, 2, Blocks.STRIPPED_WARPED_STEM), 3, -2.0F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> THE_GOLDEN_SWORD = REGISTRY.register("the_golden_sword", () -> new SwordItem(TierBase.of(3000, 4.0F, 6.0F, 1, 5, Blocks.GOLD_BLOCK), 3, -2.0F, ModCreativeTab.createProperty().fireResistant()));
    public static final RegistryObject<Item> DEEP_SICKLE = REGISTRY.register("deep_sickle", () -> new SwordItem(TierBase.of(1000, 4.0F, 6.0F, 1, 2, Blocks.MOSS_BLOCK), 3, -2.4F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> IRON_DAGGER = REGISTRY.register("iron_dagger", () -> new SwordItem(TierBase.of(1400, 4.0F, 7.0F, 1, 8, Blocks.IRON_BLOCK.asItem(), Items.IRON_INGOT), 3, -2.0F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> DEEPWARHAMMER = REGISTRY.register("deepwarhammer", () -> new SwordItem(TierBase.of(1500, 0.0F, 8.0F, 0, 5), 3, -2.3F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> SKULLCRUSHER = REGISTRY.register("skullcrusher", () -> new SwordItem(TierBase.of(1500, 0.0F, 7.0F, 0, 15), 3, -2.2F, ModCreativeTab.createProperty().fireResistant()));
    public static final RegistryObject<Item> IRONLONGSPEAR = REGISTRY.register("ironlongspear", () -> new SwordItem(TierBase.of(500, 0.0F, 3.0F, 0, 1), 3, -2.2F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> GOLDENPLUNDERINGAXE = REGISTRY.register("goldenplunderingaxe", () -> new SwordItem(TierBase.of(1200, 0.0F, 5.0F, 0, 10), 3, -2.2F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> PLUNDERINGTHEGIANTAXE = REGISTRY.register("plunderingthegiantaxe", () -> new SwordItem(TierBase.of(1300, 0.0F, 7.0F, 0, 8), 3, -2.2F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> LIGHTSWORDEVER = REGISTRY.register("lightswordever", () -> new SwordItem(TierBase.of(1000, 0.0F, 8.0F, 0, 30), 3, -2.0F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> DIAMONDBIGSWORD = REGISTRY.register("diamondbigsword", () -> new SwordItem(TierBase.of(2000, 0.0F, 9.0F, 0, 15), 3, -2.3F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> BOHEMIANEARSPOON = REGISTRY.register("bohemianearspoon", () -> new SwordItem(TierBase.of(1000, 0.0F, 5.0F, 0, 10), 3, -2.2F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> SOULRAIDINGHAMMER = REGISTRY.register("soulraidinghammer", () -> new SwordItem(TierBase.of(2000, 0.0F, 10.0F, 0, 20), 3, -2.2F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> KATANA = REGISTRY.register("katana", () -> new SwordItem(TierBase.of(1000, 0.0F, 6.0F, 0, 10), 3, -2.0F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> AMETHYSTWARHAMMER = REGISTRY.register("amethystwarhammer", () -> new SwordItem(TierBase.of(1500, 0.0F, 9.0F, 0, 25), 3, -2.0F, ModCreativeTab.createProperty()));
    //spawn egg
    public static final RegistryObject<Item> HEROBRINE_SPAWN_EGG = REGISTRY.register("herobrine_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.HEROBRINE, -10092544, -65536, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> CERIS_SPAWN_EGG = REGISTRY.register("ceris_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.CERIS, -10092442, -65281, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> ZOMBIES_SPAWN_EGG = REGISTRY.register("zombies_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.ZOMBIES, -16724941, -16751104, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> NAEUS_SPAWN_EGG = REGISTRY.register("naeus_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.NAEUS, -10066330, -3355444, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> RAIN_SPAWN_EGG = REGISTRY.register("rain_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.RAIN, -16777063, -13408513, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> ABIGAIL_SPAWN_EGG = REGISTRY.register("abigail_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.ABIGAIL, -65332, -39169, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> PATRICK_SPAWN_EGG = REGISTRY.register("patrick_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.PATRICK, -16737895, -13369345, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> BLACKBONE_SPAWN_EGG = REGISTRY.register("blackbone_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.BLACKBONE, -16777216, -10066330, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> HOGSWORTH_SPAWN_EGG = REGISTRY.register("hogsworth_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.HOGSWORTH, -26215, -13108, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> CIARA_SPAWN_EGG = REGISTRY.register("ciara_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.CIARA, -52378, -39220, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> HILDA_SPAWN_EGG = REGISTRY.register("hilda_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.HILDA, -256, -3355444, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> SOLDIERS_SPAWN_EGG = REGISTRY.register("soldiers_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.SOLDIERS, -1, -1, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> WITHERED_SKELETONS_SPAWN_EGG = REGISTRY.register("withered_skeletons_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.WITHERED_SKELETONS, -13421773, -10066330, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> DARKSHIELD_SPAWN_EGG = REGISTRY.register("darkshield_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.DARKSHIELD, -6736897, -16777216, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> DARKZOMBIE_SPAWN_EGG = REGISTRY.register("darkzombie_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.DARKZOMBIE, -16751104, -13369549, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> VORDUS_SPAWN_EGG = REGISTRY.register("vordus_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.VORDUS, -13421773, -3355648, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> WITHERSHIELD_SPAWN_EGG = REGISTRY.register("withershield_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.WITHERSHIELD, -16777216, -1, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> SKELETONSNOW_SPAWN_EGG = REGISTRY.register("skeletonsnow_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.SKELETONSNOW, -1, -13369345, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> ZOMBIESPLIGEKING_SPAWN_EGG = REGISTRY.register("zombiespligeking_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.ZOMBIESPLIGEKING, -39424, -256, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> PILGEKINGZOMBIES_SPAWN_EGG = REGISTRY.register("pilgekingzombies_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.PILGEKINGZOMBIES, -26368, -52, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> PILGEKINGZOMBIE_SPAWN_EGG = REGISTRY.register("pilgekingzombie_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.PILGEKINGZOMBIE, -256, -13108, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> PIGLINCOMMANDER_SPAWN_EGG = REGISTRY.register("piglincommander_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.PIGLINCOMMANDER, -52, -256, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> NAEUSKING_SPAWN_EGG = REGISTRY.register("naeusking_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.NAEUSKING, -6737152, -65536, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> TUSK_SPAWN_EGG = REGISTRY.register("tusk_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.TUSK, -13159, -13108, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> BROTS_SPAWN_EGG = REGISTRY.register("brots_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.BROTS, -3399168, -9175040, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> ZOMBIEPIGLINART_SPAWN_EGG = REGISTRY.register("zombiepiglinart_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.ZOMBIEPIGLINART, -1343393, -412045, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> MUTATED_SPAWN_EGG = REGISTRY.register("mutated_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.MUTATED, -5134336, -16735132, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> NAMTAR_SPAWN_EGG = REGISTRY.register("namtar_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.NAMTAR, -7274496, -12544, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> AGETHA_SPAWN_EGG = REGISTRY.register("agetha_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.AGETHA, -6710887, -3381760, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> TRICER_SPAWN_EGG = REGISTRY.register("tricer_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.TRICER, -3407872, -16777216, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> BIGUNDEADSKELETON_SPAWN_EGG = REGISTRY.register("bigundeadskeleton_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.BIGUNDEADSKELETON, -10066330, -16777216, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> ARCHER_SPAWN_EGG = REGISTRY.register("archer_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.ARCHER, -6710887, -16750951, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> DARYLL_SPAWN_EGG = REGISTRY.register("daryll_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.DARYLL, -6737152, -1, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> NULLLIKE_SPAWN_EGG = REGISTRY.register("nulllike_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.NULLLIKE, -1, -16777216, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> GIGABONE_SPAWN_EGG = REGISTRY.register("gigabone_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.GIGABONE, -10066330, -3355393, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> KLAUS_SPAWN_EGG = REGISTRY.register("klaus_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.KLAUS, -10066432, -16764109, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> KLAUS_2_SPAWN_EGG = REGISTRY.register("klaus_2_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.KLAUS_2, -6711040, -16751002, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> KRALOS_SPAWN_EGG = REGISTRY.register("kralos_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.KRALOS, -16777165, -6750157, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> ARABELLA_SPAWN_EGG = REGISTRY.register("arabella_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.ARABELLA, -3407668, -13369345, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> AZALEA_SPAWN_EGG = REGISTRY.register("azalea_spawn_egg", () -> new ForgeSpawnEggItem(ModEntities.AZALEA, -256, -16738048, ModCreativeTab.createProperty("mobs")));
    //music
    public static final RegistryObject<Item> HIMMUSIC = REGISTRY.register("himmusic", () -> new MusicItemBase("him_music_boss"));
    public static final RegistryObject<Item> CERISMUSIC = REGISTRY.register("cerismusic", () -> new MusicItemBase("ceris_boss_music"));
    public static final RegistryObject<Item> NULLMUSIC = REGISTRY.register("nullmusic", () -> new MusicItemBase("null_boss_music"));
    public static final RegistryObject<Item> BLACKBONEMUSIC = REGISTRY.register("blackbonemusic", () -> new MusicItemBase("blackbone_boss_music"));
    public static final RegistryObject<Item> PIGLINKINGMUSIC = REGISTRY.register("piglinkingmusic", () -> new MusicItemBase("piglin_king_boss_music"));
    public static final RegistryObject<Item> NAEUSMUSIC = REGISTRY.register("naeusmusic", () -> new MusicItemBase("naeus_boss_music"));
    public static final RegistryObject<Item> GUTTONMUSIC = REGISTRY.register("guttonmusic", () -> new MusicItemBase("gutton_boss_music"));
    public static final RegistryObject<Item> HIMONELIVES = REGISTRY.register("himonelives", () -> new MusicItemBase("him_onelives"));
    public static final RegistryObject<Item> KRALOSMUSIC = REGISTRY.register("kralosmusic", () -> new MusicItemBase("kralos_boss_music"));
    public static final RegistryObject<Item> KLAUSMUSIC = REGISTRY.register("klausmusic", () -> new MusicItemBase("klaus_boss_music"));

    private static RegistryObject<Item> block(RegistryObject<Block> block) {
        return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), ModCreativeTab.createProperty("items")));
    }
}