package com.rainimator.rainimatormod.registry;

import com.rainimator.rainimatormod.RainimatorMod;
import com.rainimator.rainimatormod.item.*;
import com.rainimator.rainimatormod.item.armor.*;
import com.rainimator.rainimatormod.item.shield.BlueDiamondShieldItem;
import com.rainimator.rainimatormod.item.shield.NetheriteShieldItem;
import com.rainimator.rainimatormod.item.shield.SnowShieldItem;
import com.rainimator.rainimatormod.item.sword.*;
import com.rainimator.rainimatormod.item.tool.*;
import com.rainimator.rainimatormod.registry.util.*;
import com.rainimator.rainimatormod.util.Episode;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class ModItems {
    public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, RainimatorMod.MOD_ID);
    //resources
    public static final RegistryObject<Item> SUPER_RUBY = REGISTRY.register("super_ruby", () -> new ItemBase(p -> p.tab(ModCreativeTab.items).fireResistant()));
    public static final RegistryObject<Item> ABIGAIL_SPEAR = REGISTRY.register("abigail_spear", AbigailSpearItem::new);
    public static final RegistryObject<Item> GLUTTON_SLEDGEHAMMER = REGISTRY.register("glutton_sledge_hammer", () -> new SwordItem(TierBase.of(1000, 2.0F, 8.0F, 0, 15, SUPER_RUBY), 3, -2.2F, ModCreativeTab.createProperty().fireResistant()));
    public static final RegistryObject<Item> RUBY = REGISTRY.register("ruby", () -> new ItemBase(p -> p.tab(ModCreativeTab.items)));
    public static final RegistryObject<Item> RED_GOLD_DAGGER = REGISTRY.register("red_gold_dagger", RedGoldDaggerItem::new);
    public static final RegistryObject<Item> BLACKBONE_THE_BLADE = REGISTRY.register("blackbone_the_blade", BlackBoneTheBladeItem::new);
    public static final RegistryObject<Item> BLACKBONE_THE_BLADE_SINGLE_HAND = REGISTRY.register("blackbone_the_blade_single_hand", BlackBoneTheBladeSingleHandItem::new);
    public static final RegistryObject<Item> RUBY_ORE = block(ModBlocks.RUBY_ORE);
    public static final RegistryObject<Item> DEEPSLATE_RUBY_ORE = block(ModBlocks.DEEPSLATE_RUBY_ORE);
    public static final RegistryObject<Item> RUBY_BLOCK = block(ModBlocks.RUBY_BLOCK);
    public static final RegistryObject<Item> RAW_RUBY = REGISTRY.register("raw_ruby", () -> new ItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(32)));
    public static final RegistryObject<Item> SUPER_SAPPHIRE = REGISTRY.register("super_sapphire", () -> new ItemBase(p -> p.tab(ModCreativeTab.items).fireResistant()));
    public static final RegistryObject<Item> PATRICK_HELMET = REGISTRY.register("patrick_helmet", PatrickArmorItem.Helmet::new);
    public static final RegistryObject<Item> PATRICK_CHESTPLATE = REGISTRY.register("patrick_chestplate", PatrickArmorItem.Chestplate::new);
    public static final RegistryObject<Item> PATRICK_LEGGINGS = REGISTRY.register("patrick_leggings", PatrickArmorItem.Leggings::new);
    public static final RegistryObject<Item> PATRICK_BOOTS = REGISTRY.register("patrick_boots", PatrickArmorItem.Boots::new);
    public static final RegistryObject<Item> RAIN_SWORD = REGISTRY.register("rain_sword", RainSwordItem::new);
    public static final RegistryObject<Item> HEROBRINE_TOMAHAWK = REGISTRY.register("herobrine_tomahawk", HerobrineTomahawkItem::new);
    public static final RegistryObject<Item> ZECANIRN_THE_BLADE = REGISTRY.register("zecanirn_the_blade", ZecanirnTheBladeItem::new);
    public static final RegistryObject<Item> ENDER_BIG_SWORD = REGISTRY.register("ender_big_sword", EnderBigSwordItem::new);
    public static final RegistryObject<Item> LASER_SWORD = REGISTRY.register("laser_sword", () -> new FoilSwordItemBase(TierBase.of(3000, 4.0F, 13.0F, 1, 18, ModItems.SUPER_SAPPHIRE.get(), Items.ENDER_EYE), 3, -2.4F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> MACE = REGISTRY.register("mace", () -> new SwordItem(TierBase.of(12000, 4.0F, 10.0F, 0, 10, ModItems.SUPER_SAPPHIRE), 3, -2.6F, ModCreativeTab.createProperty().fireResistant()));
    public static final RegistryObject<Item> SAPPHIRE = REGISTRY.register("sapphire", () -> new ItemBase(p -> p.tab(ModCreativeTab.items)));
    public static final RegistryObject<Item> INTELLIGENCE_TOMAHAWK = REGISTRY.register("intelligence_tomahawk", IntelligenceTomahawkItem::new);
    //sword
    public static final RegistryObject<Item> GENERAL_PATRICK_LONG_KNIVES = REGISTRY.register("general_patrick_long_knives", () -> new SwordItem(TierBase.of(2500, 4.0F, 7.0F, 0, 5, SAPPHIRE), 3, -2.0F, ModCreativeTab.createProperty().fireResistant()));
    public static final RegistryObject<Item> SOLDIERS_HALBERD = REGISTRY.register("soldiers_halberd", () -> new SwordItem(TierBase.of(1500, 4.0F, 7.0F, 0, 5, SAPPHIRE), 3, -2.0F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> SOLDIERS_WAR_HAMMER = REGISTRY.register("soldiers_war_hammer", () -> new SwordItem(TierBase.of(2000, 4.0F, 6.0F, 0, 5, SAPPHIRE), 3, -2.2F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> THE_BLUE_DAGGER = REGISTRY.register("the_blue_dagger", () -> new SwordItem(TierBase.of(2000, 4.0F, 5.0F, 1, 10, ModItems.SAPPHIRE), 3, -2.0F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> SAPPHIRE_ORE = block(ModBlocks.SAPPHIRE_ORE);
    public static final RegistryObject<Item> DEEPSLATE_SAPPHIRE_ORE = block(ModBlocks.DEEPSLATE_SAPPHIRE_ORE);
    public static final RegistryObject<Item> SAPPHIRE_BLOCK = block(ModBlocks.SAPPHIRE_BLOCK);
    //armor
    public static final RegistryObject<Item> HEROBRINE_CHESTPLATE = REGISTRY.register("herobrine_chestplate", HerobrineArmorItem.Chestplate::new);
    public static final RegistryObject<Item> RAW_SAPPHIRE = REGISTRY.register("raw_sapphire", () -> new ItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(32)));
    public static final RegistryObject<Item> HOT_IRON = REGISTRY.register("hot_iron", () -> new ItemBase(p -> p.tab(ModCreativeTab.items)));
    public static final RegistryObject<Item> HOT_GLOVES = REGISTRY.register("hot_gloves", HotGlovesItem::new);
    public static final RegistryObject<Item> BLUE_DIAMOND = REGISTRY.register("blue_diamond", BlueDiamondItem::new);
    public static final RegistryObject<Item> BLUE_DIAMOND_HELMET = REGISTRY.register("blue_diamond_helmet", BlueDiamondArmorsItem.Helmet::new);
    public static final RegistryObject<Item> BLUE_DIAMOND_CHESTPLATE = REGISTRY.register("blue_diamond_chestplate", BlueDiamondArmorsItem.Chestplate::new);
    public static final RegistryObject<Item> BLUE_DIAMOND_LEGGINGS = REGISTRY.register("blue_diamond_leggings", BlueDiamondArmorsItem.Leggings::new);
    public static final RegistryObject<Item> BLUE_DIAMOND_BOOTS = REGISTRY.register("blue_diamond_boots", BlueDiamondArmorsItem.Boots::new);
    public static final RegistryObject<Item> DIAMOND_LANCE = REGISTRY.register("diamond_lance", DiamondLanceItem::new);
    public static final RegistryObject<Item> BLUE_DIAMOND_SWORD = REGISTRY.register("blue_diamond_sword", BlueDiamondSwordItem::new);
    public static final RegistryObject<Item> WINGS_OF_SALVATION = REGISTRY.register("wings_of_salvation", WingsOfSalvationItem.Chestplate::new);
    //axe
    public static final RegistryObject<Item> DIAMOND_HATCHET = REGISTRY.register("diamond_hatchet", () -> new AxeItem(TierBase.of(1500, 4.0F, 5.0F, 2, 2, BLUE_DIAMOND), 1.0F, -2.0F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> BLUE_DIAMOND_BLOCK = block(ModBlocks.BLUE_DIAMOND_BLOCK);
    public static final RegistryObject<Item> DARK_OBSIDIAN_BLOCK = block(ModBlocks.DARK_OBSIDIAN_BLOCK);
    public static final RegistryObject<Item> ZOMBIE_HEART = REGISTRY.register("zombie_heart", ZombieHeartItem::new);
    public static final RegistryObject<Item> WITHER_BONE = REGISTRY.register("wither_bone", () -> new ItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(16).fireResistant()));
    public static final RegistryObject<Item> LOWER_BOUND_ALLOY_BONE = REGISTRY.register("lower_bound_alloy_bone", () -> new FoilItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(16).fireResistant()));
    public static final RegistryObject<Item> ICE_HEART = REGISTRY.register("ice_heart", () -> new FoilItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(1).fireResistant().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> WARRIOR_HEART = REGISTRY.register("warrior_heart", () -> new FoilItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(1).fireResistant().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> ENDER_HEART = REGISTRY.register("ender_heart", () -> new FoilItemBase(p -> p.tab(ModCreativeTab.items).durability(15).fireResistant().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> LIGHT_HEART = REGISTRY.register("light_heart", () -> new FoilItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(1).fireResistant().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> DIAMOND_PIECE = REGISTRY.register("diamond_piece", () -> new ItemBase(p -> p.tab(ModCreativeTab.items)));
    public static final RegistryObject<Item> BAO_ZHU = REGISTRY.register("bao_zhu", () -> new FoilItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(32).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> MYSTIC_ORE = block(ModBlocks.MYSTIC_ORE);
    public static final RegistryObject<Item> SOUL_PEOPLE = REGISTRY.register("soul_people", () -> new FoilItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(32).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> ENDER_STONE = REGISTRY.register("ender_stone", () -> new FoilItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(1).fireResistant().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> NEAUS_SOULS = REGISTRY.register("neaus_souls", () -> new FoilItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(32).fireResistant().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> ICED_HEART = REGISTRY.register("iced_heart", () -> new ItemBase(p -> p.tab(ModCreativeTab.items).stacksTo(1).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> RAIN_CHESTPLATE = REGISTRY.register("rain_chestplate", RainArmorItem.Chestplate::new);
    public static final RegistryObject<Item> CHIEF_OF_THE_PIG_PEOPLE_HELMET = REGISTRY.register("chief_of_the_pig_people_helmet", ChiefOfThePigPeopleArmorItem.Helmet::new);
    public static final RegistryObject<Item> CHIEF_OF_THE_PIG_PEOPLE_CHESTPLATE = REGISTRY.register("chief_of_the_pig_people_chestplate", ChiefOfThePigPeopleArmorItem.Chestplate::new);
    public static final RegistryObject<Item> CHIEF_OF_THE_PIG_PEOPLE_LEGGINGS = REGISTRY.register("chief_of_the_pig_people_leggings", ChiefOfThePigPeopleArmorItem.Leggings::new);
    public static final RegistryObject<Item> CHIEF_OF_THE_PIG_PEOPLE_BOOTS = REGISTRY.register("chief_of_the_pig_people_boots", ChiefOfThePigPeopleArmorItem.Boots::new);
    public static final RegistryObject<Item> SOLDIERS_ARMOR_HELMET = REGISTRY.register("soldiers_armor_helmet", SoldiersArmorItem.Helmet::new);
    public static final RegistryObject<Item> SOLDIERS_ARMOR_CHESTPLATE = REGISTRY.register("soldiers_armor_chestplate", SoldiersArmorItem.Chestplate::new);
    public static final RegistryObject<Item> SOLDIERS_ARMOR_LEGGINGS = REGISTRY.register("soldiers_armor_leggings", SoldiersArmorItem.Leggings::new);
    public static final RegistryObject<Item> SOLDIERS_ARMOR_BOOTS = REGISTRY.register("soldiers_armor_boots", SoldiersArmorItem.Boots::new);
    public static final RegistryObject<Item> RUBY_HELMET = REGISTRY.register("ruby_helmet", RubyarmorItem.Helmet::new);
    public static final RegistryObject<Item> RUBY_CHESTPLATE = REGISTRY.register("ruby_chestplate", RubyarmorItem.Chestplate::new);
    public static final RegistryObject<Item> RUBY_LEGGINGS = REGISTRY.register("ruby_leggings", RubyarmorItem.Leggings::new);
    public static final RegistryObject<Item> RUBY_BOOTS = REGISTRY.register("ruby_boots", RubyarmorItem.Boots::new);
    public static final RegistryObject<Item> SAPPHIRE_HELMET = REGISTRY.register("sapphire_helmet", SapphireArmorItem.Helmet::new);
    public static final RegistryObject<Item> SAPPHIRE_CHESTPLATE = REGISTRY.register("sapphire_chestplate", SapphireArmorItem.Chestplate::new);
    public static final RegistryObject<Item> SAPPHIRE_LEGGINGS = REGISTRY.register("sapphire_leggings", SapphireArmorItem.Leggings::new);
    public static final RegistryObject<Item> SAPPHIRE_BOOTS = REGISTRY.register("sapphire_boots", SapphireArmorItem.Boots::new);
    public static final RegistryObject<Item> MAGIC_HAT_HELMET = REGISTRY.register("magic_hat", MagicHatItem.Helmet::new);
    public static final RegistryObject<Item> NETHER_THE_CROWN_HELMET = REGISTRY.register("nether_the_crown_helmet", NetherTheCrownItem.Helmet::new);
    public static final RegistryObject<Item> GLUTTON_HELMET = REGISTRY.register("glutton_helmet", GluttonArmorItem.Helmet::new);
    public static final RegistryObject<Item> PIGLIN_KING_CROWN = REGISTRY.register("piglin_king_crown", PiglinKingCrownItem.Helmet::new);
    public static final RegistryObject<Item> KING_NORMAL_CROWN = REGISTRY.register("king_normal_crown", KingNormalCrownItem.Helmet::new);
    public static final RegistryObject<Item> PORKSHIRE_KING_CROWN = REGISTRY.register("porkshire_king_crown", PorkshireKingCrownItem.Helmet::new);
    //tool
    public static final RegistryObject<Item> RUBY_PICKAXE = REGISTRY.register("ruby_pickaxe", RubyPickaxeItem::new);
    public static final RegistryObject<Item> HEROBRINE_DIAMOND_PICKAXE = REGISTRY.register("herobrine_diamond_pickaxe", HerobrineDiamondPickaxeItem::new);
    public static final RegistryObject<Item> SUPER_DIAMOND_APPLE = REGISTRY.register("super_diamond_apple", SuperDiamondAppleItem::new);
    public static final RegistryObject<Item> NAEUS_SWORD = REGISTRY.register("naeus_sword", NaeusSwordItem::new);
    public static final RegistryObject<Item> NETHER_SPEAR = REGISTRY.register("nether_spear", NetherSpearItem::new);
    public static final RegistryObject<Item> LOWER_BOUND_ALLOY_FLAME_SABER = REGISTRY.register("lower_bound_alloy_flame_saber", LowerBoundAlloyFlameSaberItem::new);
    public static final RegistryObject<Item> LOWER_BOUND_NUCLEAR_REACTOR = REGISTRY.register("lower_bound_nuclear_reactor", LowerBoundNuclearReactorItem::new);
    public static final RegistryObject<Item> NIGHTMARES = REGISTRY.register("nightmares", NightmaresItem::new);
    public static final RegistryObject<Item> END_STAFF = REGISTRY.register("end_staff", EndStaffItem::new);
    public static final RegistryObject<Item> MAGIC_STARD = REGISTRY.register("magic_stard", () -> new ItemBase(p -> p.tab(ModCreativeTab.items).durability(5)));
    public static final RegistryObject<Item> LIGHT_SWORD = REGISTRY.register("light_sword", () -> new FoilSwordItemBase(TierBase.of(200, 0.0F, 5.0F, 0, 25), 3, -2.2F, ModCreativeTab.createProperty().fireResistant()));
    public static final RegistryObject<Item> SHIELD_EVER = REGISTRY.register("netherite_shield", NetheriteShieldItem::new);
    public static final RegistryObject<Item> DIVINE_CORE = REGISTRY.register("divine_core", DivineCoreItem::new);
    public static final RegistryObject<Item> SNOW_SHIELD = REGISTRY.register("snow_shield", SnowShieldItem::new);
    public static final RegistryObject<Item> FALLEN_SOUL_AXE = REGISTRY.register("fallen_soul_axe", FallenSoulAxeItem::new);
    public static final RegistryObject<Item> SEIZING_SHADOW_HALBERD = REGISTRY.register("seizing_shadow_halberd", SeizingShadowHalberdItem::new);
    public static final RegistryObject<Item> ENDER_BOOK = REGISTRY.register("ender_book", EnderBookItem::new);
    public static final RegistryObject<Item> COTTON_CANDY = REGISTRY.register("cotton_candy", CottonCandyItem::new);
    public static final RegistryObject<Item> SAPPHIRE_SWORD = REGISTRY.register("sapphire_sword", SapphireSwordItem::new);
    public static final RegistryObject<Item> RUBY_SWORD = REGISTRY.register("ruby_sword", RubySwordItem::new);
    public static final RegistryObject<Item> SAPPHIRE_AXE = REGISTRY.register("sapphire_axe", SapphireAxeItem::new);
    public static final RegistryObject<Item> RUBY_AXE = REGISTRY.register("ruby_axe", RubyAxeItem::new);
    public static final RegistryObject<Item> SAPPHIRE_PICKAXE = REGISTRY.register("sapphire_pickaxe", SapphirePickaxeItem::new);
    public static final RegistryObject<Item> RUBY_PICKAXE_1 = REGISTRY.register("ruby_pickaxe_1", RubyPickaxe1Item::new);
    public static final RegistryObject<Item> SAPPHIRE_SHOVEL = REGISTRY.register("sapphire_shovel", SapphireShovelItem::new);
    public static final RegistryObject<Item> RUBY_SHOVEL = REGISTRY.register("ruby_shovel", RubyShovelItem::new);
    public static final RegistryObject<Item> SAPPHIRE_HOE = REGISTRY.register("sapphire_hoe", SapphireHoeItem::new);
    public static final RegistryObject<Item> RUBY_HOE = REGISTRY.register("ruby_hoe", RubyHoeItem::new);
    public static final RegistryObject<Item> DIAMOND_APPLE_SUPPER = REGISTRY.register("diamond_apple_supper", DiamondAppleSupperItem::new);
    public static final RegistryObject<Item> ENDER_CURVED_SWORD = REGISTRY.register("ender_curved_sword", EnderCurvedSwordItem::new);
    public static final RegistryObject<Item> UNDER_FLOWER = REGISTRY.register("under_flower", UnderFlowerItem::new);
    public static final RegistryObject<Item> BLUE_DIAMOND_SHIELD = REGISTRY.register("blue_diamond_shield", BlueDiamondShieldItem::new);
    public static final RegistryObject<Item> BLACK_GUN = REGISTRY.register("black_gun", BlackGunItem::new);
    public static final RegistryObject<Item> BLACK_DEATH_SWORD = REGISTRY.register("black_death_sword", BlackDeathSwordItem::new);
    public static final RegistryObject<Item> PURIFICATION = REGISTRY.register("purification", PurificationItem::new);
    public static final RegistryObject<Item> MYSTERIOUS_GIFT_BOX = REGISTRY.register("mysterious_gift_box", MysteriousGiftBoxItem::new);
    public static final RegistryObject<Item> RAIN_LAZYED_SWORD = REGISTRY.register("rain_lazyed_sword", () -> new FoilSwordItemBase(TierBase.of(1500, 0.0F, 8.0F, 0, 15), 3, -2.0F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> MAGIC_ENDER_PEARL = REGISTRY.register("magic_ender_pearl", MagicEnderPearlItem::new);
    public static final RegistryObject<Item> SOUL_TOTEM = REGISTRY.register("soul_totem", SoulTotemItem::new);
    public static final RegistryObject<Item> KING_ZOMBIE_PIG_MAN_SWORD = REGISTRY.register("king_zombie_pig_man_sword", () -> new SwordItem(TierBase.of(500, 0.0F, 6.0F, 0, 25, Items.GOLD_INGOT), 3, -2.3F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> EMERALD_BLADE = REGISTRY.register("emerald_blade", () -> new SwordItem(TierBase.of(1200, 4.0F, 5.0F, 0, 3, Blocks.EMERALD_BLOCK), 3, -2.2F, ModCreativeTab.createProperty().fireResistant()));
    public static final RegistryObject<Item> BLADE_OF_THE_WHIRLWIND = REGISTRY.register("blade_of_the_whirlwind", () -> new SwordItem(TierBase.of(2500, 4.0F, 6.0F, 0, 2, Blocks.OAK_LEAVES), 3, -2.8F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> SNOW_DIAMOND_SWORD = REGISTRY.register("snow_diamond_sword", () -> new SwordItem(TierBase.of(3000, 4.0F, 6.0F, 0, 2, Blocks.SNOW_BLOCK), 3, -2.0F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> NETHER_SICKLE = REGISTRY.register("nether_sickle", () -> new SwordItem(TierBase.of(2000, 4.0F, 3.0F, 1, 2, Blocks.STRIPPED_WARPED_STEM), 3, -2.0F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> THE_GOLDEN_SWORD = REGISTRY.register("the_golden_sword", () -> new SwordItem(TierBase.of(3000, 4.0F, 6.0F, 1, 5, Blocks.GOLD_BLOCK), 3, -2.0F, ModCreativeTab.createProperty().fireResistant()));
    public static final RegistryObject<Item> DEEP_SICKLE = REGISTRY.register("deep_sickle", () -> new SwordItem(TierBase.of(1000, 4.0F, 6.0F, 1, 2, Blocks.MOSS_BLOCK), 3, -2.4F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> IRON_DAGGER = REGISTRY.register("iron_dagger", () -> new SwordItem(TierBase.of(1400, 4.0F, 7.0F, 1, 8, Blocks.IRON_BLOCK.asItem(), Items.IRON_INGOT), 3, -2.0F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> DEEP_WAR_HAMMER = REGISTRY.register("deep_war_hammer", () -> new SwordItem(TierBase.of(1500, 0.0F, 8.0F, 0, 5), 3, -2.3F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> SKULL_CRUSHER = REGISTRY.register("skull_crusher", () -> new SwordItem(TierBase.of(1500, 0.0F, 7.0F, 0, 15), 3, -2.2F, ModCreativeTab.createProperty().fireResistant()));
    public static final RegistryObject<Item> IRON_LONG_SPEAR = REGISTRY.register("iron_long_spear", () -> new SwordItem(TierBase.of(500, 0.0F, 3.0F, 0, 1), 3, -2.2F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> GOLDEN_PLUNDERING_AXE = REGISTRY.register("golden_plundering_axe", () -> new SwordItem(TierBase.of(1200, 0.0F, 5.0F, 0, 10), 3, -2.2F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> PLUNDERING_THE_GIANT_AXE = REGISTRY.register("plundering_the_giant_axe", () -> new SwordItem(TierBase.of(1300, 0.0F, 7.0F, 0, 8), 3, -2.2F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> LIGHT_SWORD_EVER = REGISTRY.register("light_sword_ever", () -> new SwordItem(TierBase.of(1000, 0.0F, 8.0F, 0, 30), 3, -2.0F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> DIAMOND_BIG_SWORD = REGISTRY.register("diamond_big_sword", () -> new SwordItem(TierBase.of(2000, 0.0F, 9.0F, 0, 15), 3, -2.3F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> SOLDIER_SPEAR = REGISTRY.register("soldier_spear", () -> new SwordItem(TierBase.of(1000, 0.0F, 5.0F, 0, 10), 3, -2.2F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> SOUL_RAIDING_HAMMER = REGISTRY.register("soul_raiding_hammer", () -> new SwordItem(TierBase.of(2000, 0.0F, 10.0F, 0, 20), 3, -2.2F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> KATANA = REGISTRY.register("katana", () -> new SwordItem(TierBase.of(1000, 0.0F, 6.0F, 0, 10), 3, -2.0F, ModCreativeTab.createProperty()));
    public static final RegistryObject<Item> AMETHYST_WAR_HAMMER = REGISTRY.register("amethyst_war_hammer", () -> new SwordItem(TierBase.of(1500, 0.0F, 9.0F, 0, 25), 3, -2.0F, ModCreativeTab.createProperty()));
    //spawn egg
    public static final RegistryObject<Item> HEROBRINE_SPAWN_EGG = REGISTRY.register("herobrine_spawn_egg", () -> new SpawnEggBase(Episode.TheStruggle,ModEntities.HEROBRINE, -10092544, -65536, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> CERIS_SPAWN_EGG = REGISTRY.register("ceris_spawn_egg", () -> new SpawnEggBase(Episode.ColdAsIce,ModEntities.CERIS, -10092442, -65281, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> ZOMBIES_SPAWN_EGG = REGISTRY.register("zombies_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.ZOMBIES, -16724941, -16751104, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> NAEUS_SPAWN_EGG = REGISTRY.register("naeus_spawn_egg", () -> new SpawnEggBase(Episode.BeginAgain,ModEntities.NAEUS, -10066330, -3355444, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> RAIN_SPAWN_EGG = REGISTRY.register("rain_spawn_egg", () -> new SpawnEggBase(Episode.TheStruggle,ModEntities.RAIN, -16777063, -13408513, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> ABIGAIL_SPAWN_EGG = REGISTRY.register("abigail_spawn_egg", () -> new SpawnEggBase(Episode.BeginAgain,ModEntities.ABIGAIL, -65332, -39169, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> PATRICK_SPAWN_EGG = REGISTRY.register("patrick_spawn_egg", () -> new SpawnEggBase(Episode.ColdAsIce,ModEntities.PATRICK, -16737895, -13369345, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> BLACKBONE_SPAWN_EGG = REGISTRY.register("blackbone_spawn_egg", () -> new SpawnEggBase(Episode.WeAreTheDanger,ModEntities.BLACKBONE, -16777216, -10066330, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> HOGSWORTH_SPAWN_EGG = REGISTRY.register("hogsworth_spawn_egg", () -> new SpawnEggBase(Episode.HardPillToSwallow,ModEntities.HOGSWORTH, -26215, -13108, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> CIARA_SPAWN_EGG = REGISTRY.register("ciara_spawn_egg", () -> new SpawnEggBase(Episode.Nightmares,ModEntities.CIARA, -52378, -39220, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> HILDA_SPAWN_EGG = REGISTRY.register("hilda_spawn_egg", () -> new SpawnEggBase(Episode.ColdAsIceRemake,ModEntities.HILDA, -256, -3355444, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> SOLDIERS_SPAWN_EGG = REGISTRY.register("soldiers_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.SOLDIERS, -1, -1, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> WITHERED_SKELETONS_SPAWN_EGG = REGISTRY.register("withered_skeletons_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.WITHERED_SKELETONS, -13421773, -10066330, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> DARK_SHIELD_SPAWN_EGG = REGISTRY.register("dark_shield_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.DARK_SHIELD, -6736897, -16777216, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> DARK_ZOMBIE_SPAWN_EGG = REGISTRY.register("dark_zombie_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.DARK_ZOMBIE, -16751104, -13369549, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> VORDUS_SPAWN_EGG = REGISTRY.register("vordus_spawn_egg", () -> new SpawnEggBase(Episode.Goodbye,ModEntities.VORDUS, -13421773, -3355648, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> WITHER_SHIELD_SPAWN_EGG = REGISTRY.register("wither_shield_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.WITHER_SHIELD, -16777216, -1, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> SKELETON_SNOW_SPAWN_EGG = REGISTRY.register("skeleton_snow_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.SKELETON_SNOW, -1, -13369345, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> ZOMBIES_PIGLIN_KING_SPAWN_EGG = REGISTRY.register("zombies_piglin_king_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.ZOMBIE_PIGLIN_KING, -39424, -256, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> PIGLIN_KING_ZOMBIES_SPAWN_EGG = REGISTRY.register("piglin_king_zombies_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.PIGLIN_KING_ZOMBIES, -26368, -52, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> PIGLIN_KING_ZOMBIE_SPAWN_EGG = REGISTRY.register("piglin_king_zombie_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.PIGLIN_KING_ZOMBIE, -256, -13108, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> PIGLIN_COMMANDER_SPAWN_EGG = REGISTRY.register("piglin_commander_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.PIGLIN_COMMANDER, -52, -256, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> NAEUS_KING_SPAWN_EGG = REGISTRY.register("naeus_king_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.NAEUS_KING, -6737152, -65536, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> TUSK_SPAWN_EGG = REGISTRY.register("tusk_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.TUSK, -13159, -13108, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> BROTS_SPAWN_EGG = REGISTRY.register("brots_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.BROTS, -3399168, -9175040, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> ZOMBIE_PIGLIN_ART_SPAWN_EGG = REGISTRY.register("zombie_piglin_art_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.ZOMBIE_PIGLIN_ART, -1343393, -412045, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> MUTATED_SPAWN_EGG = REGISTRY.register("mutated_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.MUTATED, -5134336, -16735132, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> NAMTAR_SPAWN_EGG = REGISTRY.register("namtar_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.NAMTAR, -7274496, -12544, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> AGETHA_SPAWN_EGG = REGISTRY.register("agetha_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.AGETHA, -6710887, -3381760, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> TRICER_SPAWN_EGG = REGISTRY.register("tricer_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.TRICER, -3407872, -16777216, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> BIG_UNDEAD_SKELETON_SPAWN_EGG = REGISTRY.register("big_undead_skeleton_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.BIG_UNDEAD_SKELETON, -10066330, -16777216, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> ARCHER_SPAWN_EGG = REGISTRY.register("archer_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.ARCHER, -6710887, -16750951, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> DARYLL_SPAWN_EGG = REGISTRY.register("daryll_spawn_egg", () -> new SpawnEggBase(Episode.ColdAsIce,ModEntities.DARYLL, -6737152, -1, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> NULL_LIKE_SPAWN_EGG = REGISTRY.register("null_like_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.NULL_LIKE, -1, -16777216, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> GIGABONE_SPAWN_EGG = REGISTRY.register("gigabone_spawn_egg", () -> new SpawnEggBase(Episode.WeAreTheDanger,ModEntities.GIGABONE, -10066330, -3355393, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> KLAUS_SPAWN_EGG = REGISTRY.register("klaus_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.KLAUS, -10066432, -16764109, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> KLAUS_2_SPAWN_EGG = REGISTRY.register("klaus_2_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.KLAUS_2, -6711040, -16751002, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> KRALOS_SPAWN_EGG = REGISTRY.register("kralos_spawn_egg", () -> new SpawnEggBase(Episode.None,ModEntities.KRALOS, -16777165, -6750157, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> ARABELLA_SPAWN_EGG = REGISTRY.register("arabella_spawn_egg", () -> new SpawnEggBase(Episode.ToTheVoid,ModEntities.ARABELLA, -3407668, -13369345, ModCreativeTab.createProperty("mobs")));
    public static final RegistryObject<Item> AZALEA_SPAWN_EGG = REGISTRY.register("azalea_spawn_egg", () -> new SpawnEggBase(Episode.PreachToTheChoir,ModEntities.AZALEA, -256, -16738048, ModCreativeTab.createProperty("mobs")));
    //music
    public static final RegistryObject<Item> HIM_MUSIC = REGISTRY.register("him_music", () -> new MusicItemBase("him_music_boss"));
    public static final RegistryObject<Item> CERIS_MUSIC = REGISTRY.register("ceris_music", () -> new MusicItemBase("ceris_boss_music"));
    public static final RegistryObject<Item> NULL_MUSIC = REGISTRY.register("null_music", () -> new MusicItemBase("null_boss_music"));
    public static final RegistryObject<Item> BLACKBONE_MUSIC = REGISTRY.register("blackbone_music", () -> new MusicItemBase("blackbone_boss_music"));
    public static final RegistryObject<Item> PIGLIN_KING_MUSIC = REGISTRY.register("piglin_king_music", () -> new MusicItemBase("piglin_king_boss_music"));
    public static final RegistryObject<Item> NAEUS_MUSIC = REGISTRY.register("naeus_music", () -> new MusicItemBase("naeus_boss_music"));
    public static final RegistryObject<Item> glutton_MUSIC = REGISTRY.register("glutton_music", () -> new MusicItemBase("glutton_boss_music"));
    public static final RegistryObject<Item> HIM_ONE_LIVES = REGISTRY.register("him_one_lives", () -> new MusicItemBase("him_one_lives"));
    public static final RegistryObject<Item> KRALOS_MUSIC = REGISTRY.register("kralos_music", () -> new MusicItemBase("kralos_boss_music"));
    public static final RegistryObject<Item> KLAUS_MUSIC = REGISTRY.register("klaus_music", () -> new MusicItemBase("klaus_boss_music"));

    private static RegistryObject<Item> block(RegistryObject<Block> block) {
        return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), ModCreativeTab.createProperty("items")));
    }
}